export const LIST_PRODUCT = "LIST_PRODUCT";
export const PRODUCT_VIEW = "PRODUCT_VIEW";
export const PRODUCT_EDIT = "PRODUCT_EDIT";
export const PRODUCT_UPUDATE = "PRODUCT_UPUDATE";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_ADDNEW = "PRODUCT_ADDNEW";

export const CHANGE_NOTIFY = "CHANGE_NOTIFY";
